package com.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PARENT".
 */
public class Parent {

    private Long id;
    private String uid;
    private String token;
    private String phone;
    private String alias;
    private Integer sex;
    private Long birthday;
    private String headThumb;

    public Parent() {
    }

    public Parent(Long id) {
        this.id = id;
    }

    public Parent(Long id, String uid, String token, String phone, String alias, Integer sex, Long birthday, String headThumb) {
        this.id = id;
        this.uid = uid;
        this.token = token;
        this.phone = phone;
        this.alias = alias;
        this.sex = sex;
        this.birthday = birthday;
        this.headThumb = headThumb;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAlias() {
        return alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public Long getBirthday() {
        return birthday;
    }

    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    public String getHeadThumb() {
        return headThumb;
    }

    public void setHeadThumb(String headThumb) {
        this.headThumb = headThumb;
    }

}
